version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    container_name: bot
    depends_on:
      - redis
