"""staff_name add

Revision ID: 5adaf02f40fd
Revises: d094574990e1
Create Date: 2024-03-27 17:32:35.547877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adaf02f40fd'
down_revision: Union[str, None] = 'd094574990e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('staff_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'staff_name')
    # ### end Alembic commands ###
