"""staff_db staff_id update

Revision ID: 49cb02f725b9
Revises: 53784926ea0d
Create Date: 2024-03-27 18:11:34.926954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cb02f725b9'
down_revision: Union[str, None] = '53784926ea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('staff_id', sa.BigInteger(), nullable=True))
    op.drop_column('staff', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('staff', 'staff_id')
    # ### end Alembic commands ###
