"""staff_db staff_гыуктфьу update

Revision ID: 2efbca801ba0
Revises: 49cb02f725b9
Create Date: 2024-03-27 18:30:14.514437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efbca801ba0'
down_revision: Union[str, None] = '49cb02f725b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('staff_username', sa.BigInteger(), nullable=True))
    op.drop_column('staff', 'staff_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('staff_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('staff', 'staff_username')
    # ### end Alembic commands ###
