"""event_place update

Revision ID: bcc0784141e0
Revises: e60cbfe3fac7
Create Date: 2024-04-07 18:17:25.455265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc0784141e0'
down_revision: Union[str, None] = 'e60cbfe3fac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_place')
    # ### end Alembic commands ###
