"""photo_url column

Revision ID: 4bd47eedbc8b
Revises: 3a3712ce9665
Create Date: 2024-03-11 00:37:34.376031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd47eedbc8b'
down_revision: Union[str, None] = '3a3712ce9665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'photo_url')
    # ### end Alembic commands ###
