"""add event table

Revision ID: 6e5c15700094
Revises: 82fb6b31f8f0
Create Date: 2024-02-27 22:59:25.994244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5c15700094'
down_revision: Union[str, None] = '82fb6b31f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('event_price_default', sa.Integer(), nullable=True),
    sa.Column('event_price_vip', sa.Integer(), nullable=True),
    sa.Column('event_price_deadline', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
