"""add promoter and confirmed filed

Revision ID: 82fb6b31f8f0
Revises: 71402689a3f3
Create Date: 2024-02-27 17:54:57.308294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fb6b31f8f0'
down_revision: Union[str, None] = '71402689a3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('promoter', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'confirmed')
    op.drop_column('tickets', 'promoter')
    # ### end Alembic commands ###
