"""bank_card/full_name nullable

Revision ID: b53dd2a64b99
Revises: 4bd47eedbc8b
Create Date: 2024-03-11 00:53:56.457571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53dd2a64b99'
down_revision: Union[str, None] = '4bd47eedbc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'bank_card',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'bank_card',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
